# Generated by Django 5.0.2 on 2024-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('salary', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
