# Generated by Django 5.0.2 on 2024-03-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_job_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('salary', models.CharField(max_length=122)),
                ('link', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
