# Generated by Django 5.0.2 on 2024-03-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
